wordlist:
	edictor wordlist --name=valzarpanotakana --data=../cldf/cldf-metadata.json --addon="cognacy:cogid,language_subgroup:subgroup,comment:note,conceptinsource:conceptinsource,shell:shell" --sqlite

db:
	cldf createdb ../cldf/cldf-metadata.json valzarpanotakana.sqlite
