wordlist:
	edictor wordlist --name=valzar --data=../cldf/cldf-metadata.json --addon="cognacy:cogid","language_subgroup:subgroup","comment:note","conceptinsource:conceptinsource","shell:shell"

db:
	cldf createdb ../cldf/cldf-metadata.json valzar.sqlite
